config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root      'static_pages#home'
  get 'help' => 'static_pages#help'
  get  'about' =>  'static_pages#about'
  get 'contact' =>   'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :revieweds, only: [:create, :show, :index, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy, :show] do
    resources :comments
    member do
      put "like", to: "microposts#like"
      put "dislike", to: "microposts#dislike"
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/reviewed.rb
class Reviewed < ActiveRecord::Base
  belongs_to :category
  has_many :microposts

  def average_rating
  	total_rating = 0
  	self.microposts.each do |micropost|
  		total_rating = total_rating + micropost.rating.to_f
  	end
  	average_rating = total_rating/self.microposts.count
  	return average_rating.round(2)
  end

  def rating_count
    self.microposts.count
  end
end

app/controllers/revieweds_controller.rb
class ReviewedsController < ApplicationController
	
  def create
  end

  def show
  	@reviewed = Reviewed.find(params[:id])
  	@microposts = @reviewed.microposts
  end

  def index
    @revieweds = Reviewed.all
  end

  def destroy

  end


end

app/views/revieweds/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">

  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <% if micropost.category %>
    <% if micropost.category.icon %>

        <span class="icon" data-toggle="tooltip" data-placement="top" title="<%=micropost.category.name %>"><i class="fa fa-<%=micropost.category.icon%>"></i></span>

    <% end %>
  <% end %>
  <span class="subject">
    <strong><%= link_to(micropost.subject, Reviewed.find_by(:name => micropost.subject)) %></strong>
  </span>
  <span class="content">
    <%= micropost.content %>
  </span>
  <span>
    <div class="star-rating" data-score= <%= micropost.rating %> ></div>
  </span>

  <span class="timestamp">
    <%= time_ago_in_words(micropost.created_at) %> ago.
    <span class="votes-count" data-id="<%= micropost.id %>"
      <% if micropost.get_likes.size > 0 %>
        <i class="fa fa-check-square"></i> <%= pluralize(micropost.get_likes.size, "user") %> like this.
      <% end %>
    </span>
    <%= link_to "Like", like_micropost_path(micropost), class: 'vote', method: :put, remote: true %>


    <% if current_user?(micropost.user) %>
        <%= link_to "delete", micropost, method: :delete,
     													data: { confirm: "You sure?"} %>
    <% end %>
  </span>

  <span class="timestamp">
    <% micropost.comments.each do |comment| %>
      <%= link_to gravatar_for(comment.user, size: 25), comment.user %>
      <%= link_to comment.user.name, comment.user %>
      <%= comment.comment %>
      <br>
      <%= time_ago_in_words(comment.created_at) %> ago.
      <br>
    <% end %>
  </span>

  <span class="timestamp">
    <%= form_for [micropost, Comment.new] do |f| %>
      <div>
        <%= link_to gravatar_for(current_user, size: 25), current_user %>
        <%= link_to current_user.name, current_user %>
        <%= f.text_area :comment, placeholder: "Post a comment..." %>
        <p><%= f.submit "Add Comment"%></p>
      </div>
    <% end %>
  </span>


  <script>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
    $('.star-rating').raty({
        starOn: '<%= image_path('star-on.png') %>',
        starOff: '<%= image_path('star-off.png') %>',
        path: '',
        readOnly: true,

        score: function(){
            return $(this).attr('data-score');
        }
    });
  </script>
</li>

app/views/revieweds/index.html.erb
<% provide(:title, "All Entertainment") %>
<div class="container">
	<h1>All Entertainment</h1><br>
	<table class="table table-striped table-bordered">
		<tr>
			<th>Name</th>
			<th>Category</th>
			<th>Average Rating</th>
			<th>Ratings Count</th>
		</tr>
	
		<% @revieweds.each do |reviewed| %>
		<tr>
			<td><%= link_to(reviewed.name, reviewed) %></td>
			
			<% if reviewed.category %>
				<td><%= reviewed.category.name %></td>
			<% else %>
				<td><%="N/a"%><td>
			<% end %>
	
			<% if reviewed.rating_count > 0 %>
				<td><div class="star-rating" data-score= <%= reviewed.average_rating %> ></div>(<%= reviewed.average_rating %>)</td>

			<% else %>
				<td><%=nil%><td>
			<% end %>
	
			<% if reviewed.rating_count >0%>
				<td><%= reviewed.rating_count %></td>
			<% else %>
				<td><%=nil%><td>
			<% end %>
		</tr>
		<% end %>
	</table>
</td>

<script>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
    $('.star-rating').raty({
        starOn: '<%= image_path('star-on.png') %>',
        starOff: '<%= image_path('star-off.png') %>',
        path: '',
        readOnly: true,

        score: function(){
            return $(this).attr('data-score');
        }
    });
  </script>

app/views/revieweds/show.html.erb
<% provide(:title, @reviewed.name) %>
<div class= "container">
<div class="row">
	<aside class="col-md-4">
		<section class="reviewed_info">
			<h1>
				<%= @reviewed.name %><br><br>
			</h1>
			<% if @reviewed.category %>
				<p>
					<%= @reviewed.category.name %>
					<i class="fa fa-<%= @reviewed.category.icon %>" ></i>
				</p>
			<% end %>
			<p>Average Rating: <div class="star-rating" data-score= <%= @reviewed.average_rating.round %> ></div>(<%= @reviewed.average_rating %>)</p>
		</section>
		
	</aside>
</div>
 <div class="col-md-8"> 
    <% if @reviewed.microposts.any? %>
      <h3>Reviews (<%= @reviewed.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
     
    <% end %>
  </div>
</div>


  <script>
    
    $('.star-rating').raty({
        starOn: '<%= image_path('star-on.png') %>',
        starOff: '<%= image_path('star-off.png') %>',
        path: '',
        readOnly: true,
        

        score: function(){
            return $(this).attr('data-score');
        }
    });
  </script>